source 'https://rubygems.org'
ruby '2.1.2'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.4'
# Use sqlite3 as the database for Active Record
gem 'sqlite3', '1.3.9'
# Use SCSS for stylesheets
gem 'sass-rails', '4.0.3'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '1.3.0'
# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '4.0.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
gem 'therubyracer', '0.12.1', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails', '3.1.1'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks', '2.2.2'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '0.4.0', group: :doc

# Use ActiveModel has_secure_password
gem 'bcrypt', '3.1.7'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]

# Uee nokogiri for An HTML, XML, SAX, & Reader parser
gem 'nokogiri', '1.6.3.1'

# Rails Locale Data Repository
gem 'rails-i18n', '4.0.2'

group :development, :test do
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring', '1.1.3'
  # Use Pry as your rails console
  gem 'pry-rails', '0.3.2'
  # Pry Doc is a Pry REPL plugin.
  gem 'pry-doc', '0.6.0'
  # Walk the stack in a Pry session
  gem 'pry-stack_explorer', '0.4.9.1'
  # Combine 'pry' with 'byebug'. Adds 'step', 'next', and 'continue' commands to control execution.
  gem 'pry-byebug', '1.3.3'
  # Provides a better error page for Rails and other Rack apps.
  gem 'better_errors', '1.0.1'
  # Retrieve the binding of a method's caller. Can also retrieve bindings even further up the stack
  gem 'binding_of_caller', '0.7.2'
  # tap { pp self }
  gem 'tapp', '1.4.1'
  # Hirb provides a mini view framework for console applications and uses it to improve ripl(irb)'s default inspect output. 
  gem 'hirb', '0.7.2'
  # Unicode support for hirb
  gem 'hirb-unicode', '0.0.5'
  # Great Ruby dubugging companion: pretty print Ruby objects to visualize their structure.
  gem 'awesome_print', '1.2.0'
  # Quiet Assets turns off Rails asset pipeline log.
  gem 'quiet_assets', '1.0.3'
  # rspec-rails is a testing framework
  gem 'rspec-rails', '3.0.2'
end

group :development do
  # Annotates Rails/ActiveRecord Models, routes, fixtures, and others based on the database schema.
  gem 'annotate', '2.6.5'
end

group :test do
  # implements the rspec command for Spring
  gem 'spring-commands-rspec', '1.0.2'
  # Guard::RSpec automatically run your specs
  gem 'guard-rspec', '4.3.1'
  # Acceptance test framework for web applications
  gem 'capybara', '2.4.1'
  # WebDriver is a tool for writing automated tests of websites. It aims to mimic the behaviour of a real user, and as such interacts with the HTML of the application.
  gem 'selenium-webdriver', '2.42.0'
  # factory_girl is a fixtures replacement with a straightforward definition syntax
  gem 'factory_girl_rails', '4.4.1'
  # A helper for launching cross-platform applications in a fire and forget manner.
  gem 'launchy', '2.4.2'
  # Strategies for cleaning databases
  gem 'database_cleaner', '1.3.0'
end
